### ISSUE TITLE
Package subpath './lib/connection/BaseConnection' is not defined by "exports"

### ISSUE THREAD

**Issue by woodcockjosh** [elastic/elastic-transport-js#145]
## 🐛 Bug Report

When running I get this error: ` Package subpath './lib/connection/BaseConnection' is not defined by "exports"` with version 8.8.0

## To Reproduce

Install 8.8.0
See the error when running any application

## Your Environment

node 20.11.1
linux & macos arm

**Comment by JoshMock** [comment]
Good catch. Fixing and releasing ASAP.

**Comment by JoshMock** [comment]
8.8.1 will be published in the next few minutes with the fix.
