### ISSUE TITLE
`maxResponseSize` option does not work when `content-length` header is not present in response headers

### ISSUE THREAD

**Issue by mibragimov** [elastic/elastic-transport-js#56]
## 🐛 Bug Report

The `maxResponseSize` option does not work when the content-length header is not present in the response headers. 
This is the case when the response is chunked

## To Reproduce

1. Create a client with `maxResponseSize `option set to a value smaller than the response size.
2. Make a request to an endpoint that returns a chunked response. e.g. client.asInternalUser.indices.getMapping
3. The response is not aborted when the response size is larger than the `maxResponseSize` option.

## Expected behavior

The `maxResponseSize` option should work regardless of the presence of the content-length header

## Your Environment

- *node version*: 16.18.1
- `@elastic/elasticsearch` 8.4
- *os*: Mac

**Comment by delvedor** [comment]
I've opened https://github.com/elastic/elastic-transport-js/pull/57 to address this specific issue, even tho I would recommend using the `asStream` option when you know the response will have the `'transfer-encoding': 'chunked'` header.
