### ISSUE TITLE
Version 8.2 does not work with with Nodejs 12 and below due to the new version of undici

### ISSUE THREAD

**Issue by bugb** [elastic/elastic-transport-js#74]
It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `not reproducible` label.**

## 🐛 Bug Report

- Since undici version 5.28.0, they will not support Nodejs 12 and below. It has been confirmed https://github.com/nodejs/undici/issues/2469#event-11070377134 or you can check the diff from the version v5.27 latest to the version 5.28 [here](https://github.com/nodejs/undici/compare/v5.27.2...v5.28.0#) where you can see a lot of `??` (optional chainning) and `?.` (nullish coalescing) synxtax those are not availble in Nodejs 12 and below.

- This problem happens due to the [line](https://github.com/elastic/elastic-transport-js/blob/8.2/package.json#L65) below:

![image](https://github.com/elastic/elastic-transport-js/assets/9280412/a53e5b96-1832-4543-ad7f-f09c9a6bb0e3)

undici will be resolved to the version under 6.0, due to [npm follows semver spec](https://docs.npmjs.com/about-semantic-versioning). Or you can check the online version of npm semver calculation [here](https://semver.npmjs.com/).

![image](https://github.com/elastic/elastic-transport-js/assets/9280412/7da47730-190f-4968-af59-cf9c15234d0e)

## To Reproduce

- Use elastic-transport-js version 8.2 in Nodejs 12 and below

## Expected behavior

- elastic-transport-js should work with Nodejs 12 because it is in high demand :)
[(Source)](https://www.npmjs.com/package/@elastic/transport?activeTab=versions)
![image](https://github.com/elastic/elastic-transport-js/assets/9280412/565441b0-65d2-4448-89ef-9da2b7a86d4d)

## Your Environment

- *node version*: 12 and below
- `@elastic/elasticsearch` *version*: 8.2
- *os*: Mac, Windows, Linux
- *any other relevant information*

## Additional information
- I have created a PR https://github.com/elastic/elastic-transport-js/pull/75, feel free to review it.
- When run the coverage test for both version 8.2 and 8.2.fix, the both coverage reports are indentical! 
![image](https://github.com/elastic/elastic-transport-js/assets/9280412/e8f268ab-a83f-429d-9780-a7ac86319d4d)

**Comment by JoshMock** [comment]
As noted in [the client's documentation](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/installation.html#nodejs-support), the Elasticsearch Node.js client and supporting libraries like this one will drop support for Node.js versions that have reached end of life between minor versions. Node.js v12 reached EOL in April of 2022, so we no longer support it [as of client version 8.4.0](https://github.com/elastic/elasticsearch-js/commit/8604da555fdc15871d4398af8499d1cf33f5d2b1). [Support for v14 and v16 will end](https://github.com/elastic/elasticsearch-js/pull/2055) when I ship 8.11.0 of the client in the next few days.
