### ISSUE TITLE
Support Undici v6

### ISSUE THREAD

**Issue by ralbertazzi** [elastic/elastic-transport-js#82]
## 🚀 Feature Proposal

The library currently constrains undici to `^5.22.1`. Undici v6 has been out since almost 2 months, `@elastic/transport` should support it. I don't think big breaking changes have been brought, expect that Node 16, which [has reached EOL](https://endoflife.date/nodejs), is not supported anymore ([PR](https://github.com/nodejs/undici/pull/2480)).

## Motivation

Keep up with security fixes, bug fixes, performance improvements, ...

**Comment by JoshMock** [comment]
This could also help solve [our long-running `MaxListenersExceededWarning` issue](https://github.com/elastic/elastic-transport-js/issues/63), assuming that the next Undici release includes https://github.com/nodejs/undici/pull/2823.

**Comment by JoshMock** [comment]
Waiting to tie up some loose ends on https://github.com/elastic/elastic-transport-js/pull/85. If that merges soon, v8.14.0 of the client will be running on Undici v6.
